import enum

class OrganizationRole(enum.Enum):
    OWNER = "Owner"
    CEO = "CEO"
    CTO = "CTO"
    CFO = "CFO"
    COO = "COO"
    MANAGER = "Manager"
    ADMIN = "Admin"
    TEAM_LEAD = "Team Lead"
    SENIOR_EMPLOYEE = "Senior Employee"
    JUNIOR_EMPLOYEE = "Junior Employee"
    INTERN = "Intern"
    CONSULTANT = "Consultant"
    CONTRACTOR = "Contractor"
    TEMPORARY_STAFF = "Temporary Staff"
    HR_REPRESENTATIVE = "HR Representative"
    MARKETING_SPECIALIST = "Marketing Specialist"
    SALES_REPRESENTATIVE = "Sales Representative"
    ACCOUNTANT = "Accountant"
    PRODUCT_MANAGER = "Product Manager"
    PROJECT_MANAGER = "Project Manager"
    CUSTOMER_SUPPORT = "Customer Support"