name: Python application test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  DB_CONFIG: ${{ secrets.DB_CONFIG }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  CLIENT_ID_M2M: ${{ secrets.CLIENT_ID_M2M }}
  CLIENT_SECRET_M2M: ${{ secrets.CLIENT_SECRET_M2M }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  AUDUENCE: ${{ secrets.AUDUENCE }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
  DEV_DB_HOST: ${{ secrets.DB_HOST }}
  DEV_DB_PORT: ${{ secrets.DB_PORT }}
  DEV_DB_USER: ${{ secrets.DB_USERNAME }}
  DEV_DB_PASS: ${{ secrets.DB_PASS }}
  DEV_DB_NAME: ${{ secrets.DB_NAME }}
  CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
          token: ${{ secrets.CODECOV_TOKEN }}